trigger: none

pool: ""

steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: ""
      ScriptType: "InlineScript"
      Inline: "New-AzResourceGroupDeploymentStack -Name demo-deploy-stack -ResourceGroupName exampleRG -TemplateFile main.bicep -TemplateParameterFile main.bicepparam -DenySettingsMode none -DeleteResources"
      azurePowerShellVersion: "LatestVersion"
